import Head from 'next/head'
import SideNav from '../components/sidebar';
import NavBar from '../components/navbar';
import { useState } from 'react';
import returnComponent from '../helpers/sideNavControl';

export default function Home() {
  const [sideNavOption,setSideNavOption] = useState('Dashboard');

  return (
    <div>
      <Head>
        <title>Clever Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`w-[100%] flex`}>
          <SideNav currentOption={sideNavOption} changeOption={setSideNavOption}></SideNav>
          <div className='w-[calc(100%-80px)]'>
            <NavBar></NavBar>
            <div className='main-board p-[30px]'>
                {returnComponent(sideNavOption)}
            </div>
          </div>
      </div>
    </div>
  )
}
